package com.demo.quentin.domain;

import java.math.BigDecimal;
import java.util.Date;

public class OptEwbVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.EWB_NO
     *
     * @mbggenerated
     */
    private String ewbNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.OPERATION_ID
     *
     * @mbggenerated
     */
    private Long operationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.EWB_DATE
     *
     * @mbggenerated
     */
    private Date ewbDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SEND_CUSTOMER_ID
     *
     * @mbggenerated
     */
    private Integer sendCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SEND_CUSTOMER_ADDRESS_ID
     *
     * @mbggenerated
     */
    private Integer sendCustomerAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.RECEIVE_CUSTOMER_ID
     *
     * @mbggenerated
     */
    private Integer receiveCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.RECEIVE_CUSTOMER_ADDRESS_ID
     *
     * @mbggenerated
     */
    private Integer receiveCustomerAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.PIECE
     *
     * @mbggenerated
     */
    private Integer piece;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.WEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CALC_WEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal calcWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.LENGTH
     *
     * @mbggenerated
     */
    private BigDecimal length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.WIDTH
     *
     * @mbggenerated
     */
    private BigDecimal width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.HIGH
     *
     * @mbggenerated
     */
    private BigDecimal high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.VOL
     *
     * @mbggenerated
     */
    private BigDecimal vol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.VOL_WEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal volWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.GOODS_TYPE_ID
     *
     * @mbggenerated
     */
    private Integer goodsTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.GOODS_EXPLAIN
     *
     * @mbggenerated
     */
    private String goodsExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.PAY_SIDE_ID
     *
     * @mbggenerated
     */
    private Integer paySideId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.PAY_MODE_ID
     *
     * @mbggenerated
     */
    private Integer payModeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CLASS_ID
     *
     * @mbggenerated
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.PICK_GOODS_MODE_ID
     *
     * @mbggenerated
     */
    private Integer pickGoodsModeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SMS_MODE_ID
     *
     * @mbggenerated
     */
    private Integer smsModeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.FREIGHT_CURRENCY_ID
     *
     * @mbggenerated
     */
    private Integer freightCurrencyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.INSURED_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal insuredAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.INSURED_CURRENCY_ID
     *
     * @mbggenerated
     */
    private Integer insuredCurrencyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COD_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal codCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COD_CURRENCY_ID
     *
     * @mbggenerated
     */
    private Integer codCurrencyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COD_PAY_MODE_ID
     *
     * @mbggenerated
     */
    private Integer codPayModeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.REWB_NO
     *
     * @mbggenerated
     */
    private String rewbNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.INPUT_SITE_ID
     *
     * @mbggenerated
     */
    private Integer inputSiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SEND_SITE_ID
     *
     * @mbggenerated
     */
    private Integer sendSiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SALE_EMPLOYEE_ID
     *
     * @mbggenerated
     */
    private Integer saleEmployeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.RECEIVE_EMPLOYEE_ID
     *
     * @mbggenerated
     */
    private Integer receiveEmployeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.DISPATCH_SITE_ID
     *
     * @mbggenerated
     */
    private Integer dispatchSiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.DISPATCH_EMPLOYEE_ID
     *
     * @mbggenerated
     */
    private Integer dispatchEmployeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.EC_ID
     *
     * @mbggenerated
     */
    private Integer ecId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.EC_WAREHOUSE_ID
     *
     * @mbggenerated
     */
    private Integer ecWarehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.ORDER_NO
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.BL_SIGN
     *
     * @mbggenerated
     */
    private Short blSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.REFUND_FLAG
     *
     * @mbggenerated
     */
    private Short refundFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.WITHDRAW_FLAG
     *
     * @mbggenerated
     */
    private Short withdrawFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COD_FLAG_3
     *
     * @mbggenerated
     */
    private Short codFlag3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COD_FLAG_4
     *
     * @mbggenerated
     */
    private Short codFlag4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COD_FLAG_5
     *
     * @mbggenerated
     */
    private Short codFlag5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COD_FLAG_6
     *
     * @mbggenerated
     */
    private Short codFlag6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.REMARK_CLOB_ID
     *
     * @mbggenerated
     */
    private Integer remarkClobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CREATED_BY
     *
     * @mbggenerated
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CREATED_TIME
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.MODIFIED_BY
     *
     * @mbggenerated
     */
    private Integer modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.MODIFIED_TIME
     *
     * @mbggenerated
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.RD_STATUS
     *
     * @mbggenerated
     */
    private Short rdStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.FIRST_FREIGHT_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal firstFreightCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CHECK_STATUS
     *
     * @mbggenerated
     */
    private Short checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.PICKUP_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal pickupCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.FUEL_ADD_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal fuelAddCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.EC_IN_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal ecInCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.KFSLF_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal kfslfCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.KFBXF_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal kfbxfCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COUPON
     *
     * @mbggenerated
     */
    private String coupon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COUPON_RET_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal couponRetCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SERVICE_DIP_FLAG
     *
     * @mbggenerated
     */
    private Short serviceDipFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SERVICE_FIX_FLAG
     *
     * @mbggenerated
     */
    private Short serviceFixFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.REWARD_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal rewardCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.DELIVERY_DEMAND
     *
     * @mbggenerated
     */
    private String deliveryDemand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.DATA_SOURCE
     *
     * @mbggenerated
     */
    private Short dataSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.MAIN_HEWB_NO
     *
     * @mbggenerated
     */
    private String mainHewbNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.MAIN_HEWB_NO_1
     *
     * @mbggenerated
     */
    private String mainHewbNo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SHIPPING_METHOD
     *
     * @mbggenerated
     */
    private Integer shippingMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.GOODS_CATEGORY
     *
     * @mbggenerated
     */
    private Short goodsCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CAN_GIVE_OUT
     *
     * @mbggenerated
     */
    private String canGiveOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.ISJZ
     *
     * @mbggenerated
     */
    private String isjz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.RETURN_FLAG
     *
     * @mbggenerated
     */
    private Short returnFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.OLD_EWB_NO
     *
     * @mbggenerated
     */
    private String oldEwbNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.IMG_DATE
     *
     * @mbggenerated
     */
    private Date imgDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.RETURN_DATE
     *
     * @mbggenerated
     */
    private Date returnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CAN_GIVE_OUTS
     *
     * @mbggenerated
     */
    private String canGiveOuts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.MATCH_TYPE
     *
     * @mbggenerated
     */
    private Short matchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CUSTR_QUOTE_FEE
     *
     * @mbggenerated
     */
    private BigDecimal custrQuoteFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.FREIGHT_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal freightCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.FILL_STOREHOUSE
     *
     * @mbggenerated
     */
    private Short fillStorehouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.MAPPING_VERSION
     *
     * @mbggenerated
     */
    private Long mappingVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.MAX_EDGE_LENGTH
     *
     * @mbggenerated
     */
    private BigDecimal maxEdgeLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.STAIRS_TYPE_ID
     *
     * @mbggenerated
     */
    private Integer stairsTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CARGO_TYPE_ID
     *
     * @mbggenerated
     */
    private Integer cargoTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SPECIAL_PIECE
     *
     * @mbggenerated
     */
    private Integer specialPiece;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.UPSTAIRS_NEW_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal upstairsNewCharge;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HS_OPT_EWB
     *
     * @mbggenerated
     */
    public OptEwbVO(String ewbNo, Long operationId, Date ewbDate, Integer sendCustomerId, Integer sendCustomerAddressId, Integer receiveCustomerId, Integer receiveCustomerAddressId, Integer piece, BigDecimal weight, BigDecimal calcWeight, BigDecimal length, BigDecimal width, BigDecimal high, BigDecimal vol, BigDecimal volWeight, Integer goodsTypeId, String goodsExplain, Integer paySideId, Integer payModeId, Integer classId, Integer pickGoodsModeId, Integer smsModeId, Integer freightCurrencyId, BigDecimal insuredAmount, Integer insuredCurrencyId, BigDecimal codCharge, Integer codCurrencyId, Integer codPayModeId, String rewbNo, Integer inputSiteId, Integer sendSiteId, Integer saleEmployeeId, Integer receiveEmployeeId, Integer dispatchSiteId, Integer dispatchEmployeeId, Integer ecId, Integer ecWarehouseId, String orderNo, Short blSign, Short refundFlag, Short withdrawFlag, Short codFlag3, Short codFlag4, Short codFlag5, Short codFlag6, String remark, Integer remarkClobId, Integer createdBy, Date createdTime, Integer modifiedBy, Date modifiedTime, Short rdStatus, BigDecimal firstFreightCharge, Short checkStatus, BigDecimal pickupCharge, BigDecimal fuelAddCharge, BigDecimal ecInCharge, BigDecimal kfslfCharge, BigDecimal kfbxfCharge, String coupon, BigDecimal couponRetCharge, Short serviceDipFlag, Short serviceFixFlag, BigDecimal rewardCharge, String deliveryDemand, Short dataSource, String mainHewbNo, String mainHewbNo1, Integer shippingMethod, Short goodsCategory, String canGiveOut, String isjz, Short returnFlag, String oldEwbNo, Date imgDate, Date returnDate, String canGiveOuts, Short matchType, BigDecimal custrQuoteFee, BigDecimal freightCharge, Short fillStorehouse, Long mappingVersion, BigDecimal maxEdgeLength, Integer stairsTypeId, Integer cargoTypeId, Integer specialPiece, BigDecimal upstairsNewCharge) {
        this.ewbNo = ewbNo;
        this.operationId = operationId;
        this.ewbDate = ewbDate;
        this.sendCustomerId = sendCustomerId;
        this.sendCustomerAddressId = sendCustomerAddressId;
        this.receiveCustomerId = receiveCustomerId;
        this.receiveCustomerAddressId = receiveCustomerAddressId;
        this.piece = piece;
        this.weight = weight;
        this.calcWeight = calcWeight;
        this.length = length;
        this.width = width;
        this.high = high;
        this.vol = vol;
        this.volWeight = volWeight;
        this.goodsTypeId = goodsTypeId;
        this.goodsExplain = goodsExplain;
        this.paySideId = paySideId;
        this.payModeId = payModeId;
        this.classId = classId;
        this.pickGoodsModeId = pickGoodsModeId;
        this.smsModeId = smsModeId;
        this.freightCurrencyId = freightCurrencyId;
        this.insuredAmount = insuredAmount;
        this.insuredCurrencyId = insuredCurrencyId;
        this.codCharge = codCharge;
        this.codCurrencyId = codCurrencyId;
        this.codPayModeId = codPayModeId;
        this.rewbNo = rewbNo;
        this.inputSiteId = inputSiteId;
        this.sendSiteId = sendSiteId;
        this.saleEmployeeId = saleEmployeeId;
        this.receiveEmployeeId = receiveEmployeeId;
        this.dispatchSiteId = dispatchSiteId;
        this.dispatchEmployeeId = dispatchEmployeeId;
        this.ecId = ecId;
        this.ecWarehouseId = ecWarehouseId;
        this.orderNo = orderNo;
        this.blSign = blSign;
        this.refundFlag = refundFlag;
        this.withdrawFlag = withdrawFlag;
        this.codFlag3 = codFlag3;
        this.codFlag4 = codFlag4;
        this.codFlag5 = codFlag5;
        this.codFlag6 = codFlag6;
        this.remark = remark;
        this.remarkClobId = remarkClobId;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.modifiedBy = modifiedBy;
        this.modifiedTime = modifiedTime;
        this.rdStatus = rdStatus;
        this.firstFreightCharge = firstFreightCharge;
        this.checkStatus = checkStatus;
        this.pickupCharge = pickupCharge;
        this.fuelAddCharge = fuelAddCharge;
        this.ecInCharge = ecInCharge;
        this.kfslfCharge = kfslfCharge;
        this.kfbxfCharge = kfbxfCharge;
        this.coupon = coupon;
        this.couponRetCharge = couponRetCharge;
        this.serviceDipFlag = serviceDipFlag;
        this.serviceFixFlag = serviceFixFlag;
        this.rewardCharge = rewardCharge;
        this.deliveryDemand = deliveryDemand;
        this.dataSource = dataSource;
        this.mainHewbNo = mainHewbNo;
        this.mainHewbNo1 = mainHewbNo1;
        this.shippingMethod = shippingMethod;
        this.goodsCategory = goodsCategory;
        this.canGiveOut = canGiveOut;
        this.isjz = isjz;
        this.returnFlag = returnFlag;
        this.oldEwbNo = oldEwbNo;
        this.imgDate = imgDate;
        this.returnDate = returnDate;
        this.canGiveOuts = canGiveOuts;
        this.matchType = matchType;
        this.custrQuoteFee = custrQuoteFee;
        this.freightCharge = freightCharge;
        this.fillStorehouse = fillStorehouse;
        this.mappingVersion = mappingVersion;
        this.maxEdgeLength = maxEdgeLength;
        this.stairsTypeId = stairsTypeId;
        this.cargoTypeId = cargoTypeId;
        this.specialPiece = specialPiece;
        this.upstairsNewCharge = upstairsNewCharge;
    }

    public String getEwbNo() {
        return ewbNo;
    }

    public void setEwbNo(String ewbNo) {
        this.ewbNo = ewbNo;
    }

    public Long getOperationId() {
        return operationId;
    }

    public void setOperationId(Long operationId) {
        this.operationId = operationId;
    }

    public Date getEwbDate() {
        return ewbDate;
    }

    public void setEwbDate(Date ewbDate) {
        this.ewbDate = ewbDate;
    }

    public Integer getSendCustomerId() {
        return sendCustomerId;
    }

    public void setSendCustomerId(Integer sendCustomerId) {
        this.sendCustomerId = sendCustomerId;
    }

    public Integer getSendCustomerAddressId() {
        return sendCustomerAddressId;
    }

    public void setSendCustomerAddressId(Integer sendCustomerAddressId) {
        this.sendCustomerAddressId = sendCustomerAddressId;
    }

    public Integer getReceiveCustomerId() {
        return receiveCustomerId;
    }

    public void setReceiveCustomerId(Integer receiveCustomerId) {
        this.receiveCustomerId = receiveCustomerId;
    }

    public Integer getReceiveCustomerAddressId() {
        return receiveCustomerAddressId;
    }

    public void setReceiveCustomerAddressId(Integer receiveCustomerAddressId) {
        this.receiveCustomerAddressId = receiveCustomerAddressId;
    }

    public Integer getPiece() {
        return piece;
    }

    public void setPiece(Integer piece) {
        this.piece = piece;
    }

    public BigDecimal getWeight() {
        return weight;
    }

    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    public BigDecimal getCalcWeight() {
        return calcWeight;
    }

    public void setCalcWeight(BigDecimal calcWeight) {
        this.calcWeight = calcWeight;
    }

    public BigDecimal getLength() {
        return length;
    }

    public void setLength(BigDecimal length) {
        this.length = length;
    }

    public BigDecimal getWidth() {
        return width;
    }

    public void setWidth(BigDecimal width) {
        this.width = width;
    }

    public BigDecimal getHigh() {
        return high;
    }

    public void setHigh(BigDecimal high) {
        this.high = high;
    }

    public BigDecimal getVol() {
        return vol;
    }

    public void setVol(BigDecimal vol) {
        this.vol = vol;
    }

    public BigDecimal getVolWeight() {
        return volWeight;
    }

    public void setVolWeight(BigDecimal volWeight) {
        this.volWeight = volWeight;
    }

    public Integer getGoodsTypeId() {
        return goodsTypeId;
    }

    public void setGoodsTypeId(Integer goodsTypeId) {
        this.goodsTypeId = goodsTypeId;
    }

    public String getGoodsExplain() {
        return goodsExplain;
    }

    public void setGoodsExplain(String goodsExplain) {
        this.goodsExplain = goodsExplain;
    }

    public Integer getPaySideId() {
        return paySideId;
    }

    public void setPaySideId(Integer paySideId) {
        this.paySideId = paySideId;
    }

    public Integer getPayModeId() {
        return payModeId;
    }

    public void setPayModeId(Integer payModeId) {
        this.payModeId = payModeId;
    }

    public Integer getClassId() {
        return classId;
    }

    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    public Integer getPickGoodsModeId() {
        return pickGoodsModeId;
    }

    public void setPickGoodsModeId(Integer pickGoodsModeId) {
        this.pickGoodsModeId = pickGoodsModeId;
    }

    public Integer getSmsModeId() {
        return smsModeId;
    }

    public void setSmsModeId(Integer smsModeId) {
        this.smsModeId = smsModeId;
    }

    public Integer getFreightCurrencyId() {
        return freightCurrencyId;
    }

    public void setFreightCurrencyId(Integer freightCurrencyId) {
        this.freightCurrencyId = freightCurrencyId;
    }

    public BigDecimal getInsuredAmount() {
        return insuredAmount;
    }

    public void setInsuredAmount(BigDecimal insuredAmount) {
        this.insuredAmount = insuredAmount;
    }

    public Integer getInsuredCurrencyId() {
        return insuredCurrencyId;
    }

    public void setInsuredCurrencyId(Integer insuredCurrencyId) {
        this.insuredCurrencyId = insuredCurrencyId;
    }

    public BigDecimal getCodCharge() {
        return codCharge;
    }

    public void setCodCharge(BigDecimal codCharge) {
        this.codCharge = codCharge;
    }

    public Integer getCodCurrencyId() {
        return codCurrencyId;
    }

    public void setCodCurrencyId(Integer codCurrencyId) {
        this.codCurrencyId = codCurrencyId;
    }

    public Integer getCodPayModeId() {
        return codPayModeId;
    }

    public void setCodPayModeId(Integer codPayModeId) {
        this.codPayModeId = codPayModeId;
    }

    public String getRewbNo() {
        return rewbNo;
    }

    public void setRewbNo(String rewbNo) {
        this.rewbNo = rewbNo;
    }

    public Integer getInputSiteId() {
        return inputSiteId;
    }

    public void setInputSiteId(Integer inputSiteId) {
        this.inputSiteId = inputSiteId;
    }

    public Integer getSendSiteId() {
        return sendSiteId;
    }

    public void setSendSiteId(Integer sendSiteId) {
        this.sendSiteId = sendSiteId;
    }

    public Integer getSaleEmployeeId() {
        return saleEmployeeId;
    }

    public void setSaleEmployeeId(Integer saleEmployeeId) {
        this.saleEmployeeId = saleEmployeeId;
    }

    public Integer getReceiveEmployeeId() {
        return receiveEmployeeId;
    }

    public void setReceiveEmployeeId(Integer receiveEmployeeId) {
        this.receiveEmployeeId = receiveEmployeeId;
    }

    public Integer getDispatchSiteId() {
        return dispatchSiteId;
    }

    public void setDispatchSiteId(Integer dispatchSiteId) {
        this.dispatchSiteId = dispatchSiteId;
    }

    public Integer getDispatchEmployeeId() {
        return dispatchEmployeeId;
    }

    public void setDispatchEmployeeId(Integer dispatchEmployeeId) {
        this.dispatchEmployeeId = dispatchEmployeeId;
    }

    public Integer getEcId() {
        return ecId;
    }

    public void setEcId(Integer ecId) {
        this.ecId = ecId;
    }

    public Integer getEcWarehouseId() {
        return ecWarehouseId;
    }

    public void setEcWarehouseId(Integer ecWarehouseId) {
        this.ecWarehouseId = ecWarehouseId;
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public Short getBlSign() {
        return blSign;
    }

    public void setBlSign(Short blSign) {
        this.blSign = blSign;
    }

    public Short getRefundFlag() {
        return refundFlag;
    }

    public void setRefundFlag(Short refundFlag) {
        this.refundFlag = refundFlag;
    }

    public Short getWithdrawFlag() {
        return withdrawFlag;
    }

    public void setWithdrawFlag(Short withdrawFlag) {
        this.withdrawFlag = withdrawFlag;
    }

    public Short getCodFlag3() {
        return codFlag3;
    }

    public void setCodFlag3(Short codFlag3) {
        this.codFlag3 = codFlag3;
    }

    public Short getCodFlag4() {
        return codFlag4;
    }

    public void setCodFlag4(Short codFlag4) {
        this.codFlag4 = codFlag4;
    }

    public Short getCodFlag5() {
        return codFlag5;
    }

    public void setCodFlag5(Short codFlag5) {
        this.codFlag5 = codFlag5;
    }

    public Short getCodFlag6() {
        return codFlag6;
    }

    public void setCodFlag6(Short codFlag6) {
        this.codFlag6 = codFlag6;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getRemarkClobId() {
        return remarkClobId;
    }

    public void setRemarkClobId(Integer remarkClobId) {
        this.remarkClobId = remarkClobId;
    }

    public Integer getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    public Integer getModifiedBy() {
        return modifiedBy;
    }

    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Date getModifiedTime() {
        return modifiedTime;
    }

    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    public Short getRdStatus() {
        return rdStatus;
    }

    public void setRdStatus(Short rdStatus) {
        this.rdStatus = rdStatus;
    }

    public BigDecimal getFirstFreightCharge() {
        return firstFreightCharge;
    }

    public void setFirstFreightCharge(BigDecimal firstFreightCharge) {
        this.firstFreightCharge = firstFreightCharge;
    }

    public Short getCheckStatus() {
        return checkStatus;
    }

    public void setCheckStatus(Short checkStatus) {
        this.checkStatus = checkStatus;
    }

    public BigDecimal getPickupCharge() {
        return pickupCharge;
    }

    public void setPickupCharge(BigDecimal pickupCharge) {
        this.pickupCharge = pickupCharge;
    }

    public BigDecimal getFuelAddCharge() {
        return fuelAddCharge;
    }

    public void setFuelAddCharge(BigDecimal fuelAddCharge) {
        this.fuelAddCharge = fuelAddCharge;
    }

    public BigDecimal getEcInCharge() {
        return ecInCharge;
    }

    public void setEcInCharge(BigDecimal ecInCharge) {
        this.ecInCharge = ecInCharge;
    }

    public BigDecimal getKfslfCharge() {
        return kfslfCharge;
    }

    public void setKfslfCharge(BigDecimal kfslfCharge) {
        this.kfslfCharge = kfslfCharge;
    }

    public BigDecimal getKfbxfCharge() {
        return kfbxfCharge;
    }

    public void setKfbxfCharge(BigDecimal kfbxfCharge) {
        this.kfbxfCharge = kfbxfCharge;
    }

    public String getCoupon() {
        return coupon;
    }

    public void setCoupon(String coupon) {
        this.coupon = coupon;
    }

    public BigDecimal getCouponRetCharge() {
        return couponRetCharge;
    }

    public void setCouponRetCharge(BigDecimal couponRetCharge) {
        this.couponRetCharge = couponRetCharge;
    }

    public Short getServiceDipFlag() {
        return serviceDipFlag;
    }

    public void setServiceDipFlag(Short serviceDipFlag) {
        this.serviceDipFlag = serviceDipFlag;
    }

    public Short getServiceFixFlag() {
        return serviceFixFlag;
    }

    public void setServiceFixFlag(Short serviceFixFlag) {
        this.serviceFixFlag = serviceFixFlag;
    }

    public BigDecimal getRewardCharge() {
        return rewardCharge;
    }

    public void setRewardCharge(BigDecimal rewardCharge) {
        this.rewardCharge = rewardCharge;
    }

    public String getDeliveryDemand() {
        return deliveryDemand;
    }

    public void setDeliveryDemand(String deliveryDemand) {
        this.deliveryDemand = deliveryDemand;
    }

    public Short getDataSource() {
        return dataSource;
    }

    public void setDataSource(Short dataSource) {
        this.dataSource = dataSource;
    }

    public String getMainHewbNo() {
        return mainHewbNo;
    }

    public void setMainHewbNo(String mainHewbNo) {
        this.mainHewbNo = mainHewbNo;
    }

    public String getMainHewbNo1() {
        return mainHewbNo1;
    }

    public void setMainHewbNo1(String mainHewbNo1) {
        this.mainHewbNo1 = mainHewbNo1;
    }

    public Integer getShippingMethod() {
        return shippingMethod;
    }

    public void setShippingMethod(Integer shippingMethod) {
        this.shippingMethod = shippingMethod;
    }

    public Short getGoodsCategory() {
        return goodsCategory;
    }

    public void setGoodsCategory(Short goodsCategory) {
        this.goodsCategory = goodsCategory;
    }

    public String getCanGiveOut() {
        return canGiveOut;
    }

    public void setCanGiveOut(String canGiveOut) {
        this.canGiveOut = canGiveOut;
    }

    public String getIsjz() {
        return isjz;
    }

    public void setIsjz(String isjz) {
        this.isjz = isjz;
    }

    public Short getReturnFlag() {
        return returnFlag;
    }

    public void setReturnFlag(Short returnFlag) {
        this.returnFlag = returnFlag;
    }

    public String getOldEwbNo() {
        return oldEwbNo;
    }

    public void setOldEwbNo(String oldEwbNo) {
        this.oldEwbNo = oldEwbNo;
    }

    public Date getImgDate() {
        return imgDate;
    }

    public void setImgDate(Date imgDate) {
        this.imgDate = imgDate;
    }

    public Date getReturnDate() {
        return returnDate;
    }

    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

    public String getCanGiveOuts() {
        return canGiveOuts;
    }

    public void setCanGiveOuts(String canGiveOuts) {
        this.canGiveOuts = canGiveOuts;
    }

    public Short getMatchType() {
        return matchType;
    }

    public void setMatchType(Short matchType) {
        this.matchType = matchType;
    }

    public BigDecimal getCustrQuoteFee() {
        return custrQuoteFee;
    }

    public void setCustrQuoteFee(BigDecimal custrQuoteFee) {
        this.custrQuoteFee = custrQuoteFee;
    }

    public BigDecimal getFreightCharge() {
        return freightCharge;
    }

    public void setFreightCharge(BigDecimal freightCharge) {
        this.freightCharge = freightCharge;
    }

    public Short getFillStorehouse() {
        return fillStorehouse;
    }

    public void setFillStorehouse(Short fillStorehouse) {
        this.fillStorehouse = fillStorehouse;
    }

    public Long getMappingVersion() {
        return mappingVersion;
    }

    public void setMappingVersion(Long mappingVersion) {
        this.mappingVersion = mappingVersion;
    }

    public BigDecimal getMaxEdgeLength() {
        return maxEdgeLength;
    }

    public void setMaxEdgeLength(BigDecimal maxEdgeLength) {
        this.maxEdgeLength = maxEdgeLength;
    }

    public Integer getStairsTypeId() {
        return stairsTypeId;
    }

    public void setStairsTypeId(Integer stairsTypeId) {
        this.stairsTypeId = stairsTypeId;
    }

    public Integer getCargoTypeId() {
        return cargoTypeId;
    }

    public void setCargoTypeId(Integer cargoTypeId) {
        this.cargoTypeId = cargoTypeId;
    }

    public Integer getSpecialPiece() {
        return specialPiece;
    }

    public void setSpecialPiece(Integer specialPiece) {
        this.specialPiece = specialPiece;
    }

    public BigDecimal getUpstairsNewCharge() {
        return upstairsNewCharge;
    }

    public void setUpstairsNewCharge(BigDecimal upstairsNewCharge) {
        this.upstairsNewCharge = upstairsNewCharge;
    }

    @Override
    public String toString() {
        return "OptEwbVO{" +
                "ewbNo='" + ewbNo + '\'' +
                ", operationId=" + operationId +
                ", ewbDate=" + ewbDate +
                ", sendCustomerId=" + sendCustomerId +
                ", sendCustomerAddressId=" + sendCustomerAddressId +
                ", receiveCustomerId=" + receiveCustomerId +
                ", receiveCustomerAddressId=" + receiveCustomerAddressId +
                ", piece=" + piece +
                ", weight=" + weight +
                ", calcWeight=" + calcWeight +
                ", length=" + length +
                ", width=" + width +
                ", high=" + high +
                ", vol=" + vol +
                ", volWeight=" + volWeight +
                ", goodsTypeId=" + goodsTypeId +
                ", goodsExplain='" + goodsExplain + '\'' +
                ", paySideId=" + paySideId +
                ", payModeId=" + payModeId +
                ", classId=" + classId +
                ", pickGoodsModeId=" + pickGoodsModeId +
                ", smsModeId=" + smsModeId +
                ", freightCurrencyId=" + freightCurrencyId +
                ", insuredAmount=" + insuredAmount +
                ", insuredCurrencyId=" + insuredCurrencyId +
                ", codCharge=" + codCharge +
                ", codCurrencyId=" + codCurrencyId +
                ", codPayModeId=" + codPayModeId +
                ", rewbNo='" + rewbNo + '\'' +
                ", inputSiteId=" + inputSiteId +
                ", sendSiteId=" + sendSiteId +
                ", saleEmployeeId=" + saleEmployeeId +
                ", receiveEmployeeId=" + receiveEmployeeId +
                ", dispatchSiteId=" + dispatchSiteId +
                ", dispatchEmployeeId=" + dispatchEmployeeId +
                ", ecId=" + ecId +
                ", ecWarehouseId=" + ecWarehouseId +
                ", orderNo='" + orderNo + '\'' +
                ", blSign=" + blSign +
                ", refundFlag=" + refundFlag +
                ", withdrawFlag=" + withdrawFlag +
                ", codFlag3=" + codFlag3 +
                ", codFlag4=" + codFlag4 +
                ", codFlag5=" + codFlag5 +
                ", codFlag6=" + codFlag6 +
                ", remark='" + remark + '\'' +
                ", remarkClobId=" + remarkClobId +
                ", createdBy=" + createdBy +
                ", createdTime=" + createdTime +
                ", modifiedBy=" + modifiedBy +
                ", modifiedTime=" + modifiedTime +
                ", rdStatus=" + rdStatus +
                ", firstFreightCharge=" + firstFreightCharge +
                ", checkStatus=" + checkStatus +
                ", pickupCharge=" + pickupCharge +
                ", fuelAddCharge=" + fuelAddCharge +
                ", ecInCharge=" + ecInCharge +
                ", kfslfCharge=" + kfslfCharge +
                ", kfbxfCharge=" + kfbxfCharge +
                ", coupon='" + coupon + '\'' +
                ", couponRetCharge=" + couponRetCharge +
                ", serviceDipFlag=" + serviceDipFlag +
                ", serviceFixFlag=" + serviceFixFlag +
                ", rewardCharge=" + rewardCharge +
                ", deliveryDemand='" + deliveryDemand + '\'' +
                ", dataSource=" + dataSource +
                ", mainHewbNo='" + mainHewbNo + '\'' +
                ", mainHewbNo1='" + mainHewbNo1 + '\'' +
                ", shippingMethod=" + shippingMethod +
                ", goodsCategory=" + goodsCategory +
                ", canGiveOut='" + canGiveOut + '\'' +
                ", isjz='" + isjz + '\'' +
                ", returnFlag=" + returnFlag +
                ", oldEwbNo='" + oldEwbNo + '\'' +
                ", imgDate=" + imgDate +
                ", returnDate=" + returnDate +
                ", canGiveOuts='" + canGiveOuts + '\'' +
                ", matchType=" + matchType +
                ", custrQuoteFee=" + custrQuoteFee +
                ", freightCharge=" + freightCharge +
                ", fillStorehouse=" + fillStorehouse +
                ", mappingVersion=" + mappingVersion +
                ", maxEdgeLength=" + maxEdgeLength +
                ", stairsTypeId=" + stairsTypeId +
                ", cargoTypeId=" + cargoTypeId +
                ", specialPiece=" + specialPiece +
                ", upstairsNewCharge=" + upstairsNewCharge +
                '}';
    }
}